File upload and validation
yelenskaya/carRecording pull request #1
Opened 2022-12-07 09:47 UTC by yelenskaya

2022-12-07 10:14 UTC, DenysMoskalenko requested changes

2022-12-07 10:14 UTC, DenysMoskalenko commented on file_validation.py
> +    headers = next(csv_reader)
1) Эта переменная не используется?
2) Хедерсы ты не валидируешь, почему?

2022-12-07 10:14 UTC, DenysMoskalenko commented on file_validation.py
> +    for i, line in enumerate(csv_reader, start=1):
Давай не i, а что-то более реальное, line_number, row_number и тд тп. Если есть шанс сделать понятнее - лучше сделать

2022-12-07 10:14 UTC, DenysMoskalenko commented on file_validation.py
> +        raise HTTPException(
Давай не вызывать HTTPException.
Допустим ты захочешь использовать этот валидатор в отрыве от ендпоинта, в каком-то скрипте, в таком случае все кончится плохо.
Я бы сделал кастомную ошибку и вызывал её

2022-12-07 10:14 UTC, DenysMoskalenko commented on file_validation.py
> +        _raise_if_broken_timeline(int(timestamp), last_timestamp, i)
в функции _get_timestamp_and_data ты говоришь, что возвращается int, но тут опять приводишь к int

2022-12-07 10:14 UTC, DenysMoskalenko commented on file_validation.py
> +    last_timestamp = None
Сделай 0 и не мучайся с None

2022-12-07 10:14 UTC, DenysMoskalenko commented on file_validation.py
> +    if last_timestamp and timestamp < last_timestamp:
Я думаю если 2 сигнала прийдут с одинаковым таймстемпом (по миллисекундам это вполне возможно) - то это валидное поведение
Т.е. тут скорее всего <=
Если не прав - скажи, пожалуйста

2022-12-07 10:14 UTC, DenysMoskalenko commented on models.py
> +from pydantic import BaseModel, Extra
Назови файл schemas
models всегда фигурирует с БД и происходит путаница

2022-12-07 10:25 UTC, DenysMoskalenko commented on app.py
> +from time import time
Можешь попробовать использовать какую-то либу для построенния проекта.
Первое что нашел - https://github.com/ycd/manage-fastapi
Посмотреть че оно построит. Думаю там должна быть норм структура (сам не проверял)

2022-12-07 14:42 UTC, yelenskaya commented on file_validation.py
> +    upload_file.file.seek(0)
Да, там есть асинк read и seek. Не могу понять как определить что нужна асинхронность ( У меня сложилось впечатление, что если программа не может дальше пойти пока не закончится операция, то надо синхронные использовать

2022-12-07 15:08 UTC, yelenskaya commented on file_validation.py
> +    csv_reader = reader(file_object)
То в авс было. Чекнула, работает, но не знаю, есть ли смысл менять

2022-12-07 15:20 UTC, DenysMoskalenko commented on file_validation.py
> +    upload_file.file.seek(0)
a = await get_a()
b = await get_b(a=a)

У тебя никога не будет ошибки, потому, что у тебя программа не пойдет дальше, она будет синхронно ждать, пока у тебя выполнится get_a() потом, пока выполнится get_b(). Просто в этот момент, пока ты ждешь у тебя сервер может обработать другой запрос и мощности процессора не будут блокироваться.

Бояться нужно, если б у тебя было:
Паралелизация в случае асинхронности делается с помощью asyncio.gather() например. Вот тогда да, они будут у тебя выполняться паралельно, как мы делали в многопоточности. А в случае, когда ты пишешь просто await - у тебя по сути код отрабатывает синхронно, но процессор в момент ожидания может сделать что-то ещё из-за чего производительность многократно увеличивается.

Если например ты сделаешь
```
for i in range(10):
    await request_data_from_api()
```
Не будет никакой разницы, если б ты вызывала это синхронно и время выполнения идентичное. 
Чтоб Сделалось паралельно, надо так-же как и в многопоточности собрать таски и потом закинуть их, например, в await gather(*tasks)

2022-12-07 15:24 UTC, DenysMoskalenko commented on file_validation.py
> +    upload_file.file.seek(0)
И момент номер два, когда у тебя в асинхронной програме встречается синхронный вызов - у тебя ломается почти вся суть асинхронности этого ендпоинта. Вся цепочка идет по одному месту.
У тебя сейчас такая ситуация есть с boto3 - ведь она синхронна. В идеале её нужно заменить на aioboto3 или напрямую использовать асинхронную сессию из aiobotocore.
Либо, как самый вариант минимум - обернуть эту функцию в асинхронную фунцию - это не выиграет ничего в плане производительности, ведь используя асинхронную сессиию сам авс работает лучше, но выиграет немного с точки зрения что сам процессор сервера не будет блокирован.
Последний вариант мы с тобой и возьмем чуть позже, просто чтоб ознакомится, но в реальных проектах я тебе запрещаю такое делать (ну разве что в самых отчаяных случаях)

2022-12-07 15:25 UTC, DenysMoskalenko commented on file_validation.py
> +    csv_reader = reader(file_object)
Ап ту ю

2022-12-07 15:53 UTC, yelenskaya commented on file_validation.py
> +        raise HTTPException(
Не уверена насчет этого. Я эту валидацию подключаю через депенденси,  если что-то не так, то он бросает эксепшен с которым фаст апи знает что делать, а если кастомный бросать то наверное будет сервер эррор и все. Ну или тогда вызывать уже в самой функции роута его и обрабатывать

2022-12-07 15:57 UTC, yelenskaya commented on file_validation.py
> +    if last_timestamp and timestamp < last_timestamp:
Если равно - валидное, а тут условие - бросать эксепшен если меньше. Т.е. если больше или равно то все ок

2022-12-07 16:12 UTC, yelenskaya commented on models.py
> +    class Config:
О, прикольно

2022-12-07 16:19 UTC, yelenskaya commented on file_validation.py
> +    upload_file.file.seek(0)
Спасибо за объяснение

2022-12-07 17:37 UTC, DenysMoskalenko commented on file_validation.py
> +        raise HTTPException(
Ты можешь сделать функцию-оббертку, которую будешь вызывать в депенденси,
Либо делать валидацию файла вне депенденси

2022-12-07 17:57 UTC, DenysMoskalenko requested changes

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/file_validation.py
> +CSV_HEADERS = ['timestamp', 'data']
Если константа - наверное должен быть тюпл?

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/file_validation.py
> +            detail=f'File headers are invalid. Allowed headers are {CSV_HEADERS}, got {headers}')
Скобка закрытая должна быть на новой строчке

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/file_validation.py
> +def _get_timestamp_and_data(line: str, line_number: int) -> tuple[int, dict]:
А если добавится какое-то поле, тоже его допишешь в функцию?
Я предлагаю сделать какое-то более общее название, типо parse_row

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/file_validation.py
> +        timestamp, data = line
По идее, если у тебя провалижировались хедерсы - это гарантирует, что у тебя есть 2 столбца и мы сюда никогда не попадем

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/file_validation.py
> +        data = json.loads(data)
Используй orjson.
Не помню говорил ли про него, раньше - это скомпилированная на С либо, которая работает сильно быстрее.
У нее есть минус, что она кодирует в байты, а не строку в отличие от обычного, но декодирует всегда правильно.
+ она нам пригодится когда будем в сокеты слать сообщение.

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/main.py
> +from .routes import router
Не используй относительные импорты

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/routes.py
> +router = APIRouter(
Если влазит в строчку, я бы оставлял строчкой - меньше полотно это хорошо. Но тут на любителя

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/settings.py
> +    s3_bucket: str = Field(..., env="S3_BUCKET")
Это константа - сделай большими

2022-12-07 17:57 UTC, DenysMoskalenko commented on pyproject.toml
> +factory-boy = "^3.2.1"
Где линтер?

2022-12-07 17:57 UTC, DenysMoskalenko commented on pyproject.toml
> +python-dotenv = "^0.21.0"
Эта либа вроде не используется больше

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/settings.py
> +    s3_bucket: str = Field(..., env="S3_BUCKET")
Тебе не нужно делать field 
Снимет сами поймут что им надо считать с энва. Просто пиши как в обычной схеме

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/settings.py
> +settings = Settings()
Давай не будем делать глобальный объект.
Сделай функцию get_settings()
Повесь на нее lru_cache и дергай как депенденси туда где надо

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/routes.py
> +s3_client = client('s3')
Создавать с3 клиента в конкретном роуте - плохая затея.
Если нужно будет в другом месте программы, что будешь делать?

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/routes.py
> +s3_client = client('s3')
Давай не создавать глобальный объект.
Сделай функцию в сетингах, повесь кеш и используй как депенденси

2022-12-07 17:57 UTC, DenysMoskalenko commented on app/routes.py
> +    return S3RecordingSchema(recording_id=recording_id)
Просто для инфы - тебе не обязательно прописывать схему в ответе, ты можешь отдать словарь, фастапи само приведет к схеме, которую ты указала.
(По этому мы не пишем тайпхинт на респонс этой функции)

2022-12-08 09:16 UTC, yelenskaya commented on app/file_validation.py
> +        timestamp, data = line
Ну я вполне могу добавить лишнее поле в цсв в любой ряд

2022-12-08 09:29 UTC, yelenskaya commented on pyproject.toml
> +python-dotenv = "^0.21.0"
Она нужна, чтоб загрузка из энв переменных работала через сеттинги

2022-12-08 10:31 UTC, yelenskaya commented on app/routes.py
> +s3_client = client('s3')
Как ты понимаешь, что класть в lru cache?

2022-12-08 10:53 UTC, DenysMoskalenko requested changes

2022-12-08 10:53 UTC, DenysMoskalenko commented on .flake8
> +max-line-length = 120
а импорт одер?

2022-12-08 10:53 UTC, DenysMoskalenko commented on app/file_validation.py
> +        timestamp, data = line
Тогда у тебя csv_reader прочитает хедер для этого поля как None и оно не будет равно с твоими хедерами

2022-12-08 10:53 UTC, DenysMoskalenko commented on app/routes.py
> +from fastapi import HTTPException, UploadFile
А зачем 2 строчки тут?

2022-12-08 11:01 UTC, yelenskaya commented on pyproject.toml
> +python-dotenv = "^0.21.0"
*записывает в долговую книжку*

2022-12-08 11:11 UTC, yelenskaya commented on pyproject.toml
> +python-dotenv = "^0.21.0"
*вычеркивает из книжки*

2022-12-08 11:23 UTC, DenysMoskalenko approved these changes

2022-12-08 11:37 UTC, merged