SQS listener
yelenskaya/carRecording pull request #10
Opened 2023-01-19 13:58 UTC by yelenskaya

2023-01-19 14:25 UTC, DenysMoskalenko requested changes

2023-01-19 14:25 UTC, DenysMoskalenko commented on recording/app/main.py
> +@app.on_event('startup')
тебе не нужно вешать на стартап если ты делаешь его повторяемым.

2023-01-19 14:25 UTC, DenysMoskalenko commented on recording/app/main.py
> +@app.on_event('startup')
Идея вешать на стартап было б валидна, елси б ты ранила какой-то отдельный процесс, который жил б там все время работы программы

2023-01-19 14:25 UTC, DenysMoskalenko commented on recording/app/sqs_listener.py
> +        await message.delete()
а зачем тогда метод delete_message.
+ не уверен насколько коректно их удалять в любом случае.
ДОпустим ты получила 10 сообщений. В средине, допустим 6-е не валидное и выдало ошибку. Но исходя из логики контекст менеджера - ты удалишь все 10 сообщений, включая валидные, которые идут после 6-го

2023-01-19 14:25 UTC, DenysMoskalenko commented on recording/app/s3_manager.py
> +            raise
raise e тогда?
Просто raise ты вызовешь верхнюю Exception

2023-01-19 14:25 UTC, DenysMoskalenko commented on recording/app/routes.py
> +    if not check_if_file_exists(s3, settings.S3_BUCKET, object_key):
тут вкусовщина, но по мне называть что-то check_something. Предполагается что оно прочекает и если чет не так - даст ошибку (Например кастомную)
А что проверить что-то то пишется типо is_vlaid_file. (if not is_file_exist) и тд.

P.S. Это просто отсебятина

2023-01-19 14:25 UTC, DenysMoskalenko commented on recording/app/recording_reproduction.py
>      async with LockRecording(recording_id):
У тебя могут зарайзится ошибки выше, но ты все равно начнешь чет локать и пытаться делать

2023-01-19 14:25 UTC, DenysMoskalenko commented on recording/app/recording_reproduction.py
> +async def reproduce_sqs_requests():
мне не нравится имя функции.

2023-01-19 14:26 UTC, yelenskaya commented on recording/app/main.py
> +@app.on_event('startup')
Вроде надо, т.к. оно повторяется после первого запуска, если я все правильно поняла.\

2023-01-19 14:27 UTC, yelenskaya commented on recording/app/sqs_listener.py
> +        await message.delete()
Ой, не заменила

2023-01-19 14:29 UTC, yelenskaya commented on recording/app/sqs_listener.py
> +        await message.delete()
Удалять надо, иначе sqs их будет перепосылать. Но твой кейс проверю

2023-01-19 14:35 UTC, DenysMoskalenko commented on recording/app/main.py
> +@app.on_event('startup')
Ну может ты права, я не помню

2023-01-19 14:35 UTC, yelenskaya commented on recording/app/s3_manager.py
> +            raise
Не поняла. Вроде оно будет рейзить тот эксепшен, который у тебя в блоке активный 
![image](https://user-images.githubusercontent.com/45938314/213469913-c44d47bd-34d5-4ca9-82c0-e1faec24ac87.png)
![image](https://user-images.githubusercontent.com/45938314/213469996-683f817e-4219-4629-a23c-43eb93d7de2c.png)

2023-01-19 14:36 UTC, yelenskaya commented on recording/app/routes.py
> +    if not check_if_file_exists(s3, settings.S3_BUCKET, object_key):
переименовала в does_file_exists

2023-01-19 14:36 UTC, DenysMoskalenko commented on recording/app/sqs_listener.py
> +        await message.delete()
Удалять надо но не все.
1) Ты обязательно должна удалять обработанные
2) В нашем случае мы договорились логать и удалять зафейленные (в продакшене ты б скорее всего их куда-то слала ещё, где б они уже умирали)

Не обработанные удалять ненадо

2023-01-19 14:42 UTC, yelenskaya commented on recording/app/recording_reproduction.py
> +async def reproduce_sqs_requests():
trigger_reproduction_sqs ?

2023-01-19 14:45 UTC, DenysMoskalenko commented on recording/app/recording_reproduction.py
> +async def reproduce_sqs_requests():
1) Давай общаться по таким вопросам в месенджере, так всем будет в 1000 раз удобнее.
2) Я не понимаю что значит reproduction_sqs. По сути тут ты обрабатываешь sqs сообщения. Внутри этой функции ты вызываешь воспроизведение рекординга. ЧТо такое reproduction_sqs?

2023-01-20 10:58 UTC, DenysMoskalenko commented on recording/app/sqs_listener.py
> +    errors = []
А зачем ты собираешь ошибки?
Мне кажется тут должно работать по цепочке обязаностей. ТЫ проверяешь структуру сообщения - если она не правильная - выбрасываешь ошибку, процесс заканчивается. Зачем ты пытаешься продолжать что-то делать?

2023-01-20 11:06 UTC, yelenskaya commented on recording/app/sqs_listener.py
> +    errors = []
Мда, и правда

2023-01-20 11:53 UTC, DenysMoskalenko approved these changes

2023-01-20 11:55 UTC, merged