Reproduce recording
yelenskaya/carRecording pull request #3
Opened 2022-12-15 14:04 UTC by yelenskaya

2022-12-15 14:54 UTC, DenysMoskalenko requested changes

2022-12-15 14:54 UTC, DenysMoskalenko commented on app/routes.py
> +    recording_id = f'{uuid4()}-{upload_file.filename.replace(".csv", "")}'
Мне не нравится идея хранить файлы без расширения

2022-12-15 14:54 UTC, DenysMoskalenko commented on app/routes.py
> +    recording_id = f'{uuid4()}-{upload_file.filename.replace(".csv", "")}'
Как вариант кстати можно хранить рекординги не просто файлами а папками, типо:
recording_id/record.csv

В таком случае к ним можно будет например добавить какой-то metadata.json файл  с какими-то доп данными по машинке или там video.mp4 Есил например у тебя вместе с записью есть видео с регистратора.
С точки зрения авс работать это будет одинаково быстро, S3 не знает что такое папки и для неё все одинаково нормас.
Просто для сведения - хочешь сделай, хочешь не

2022-12-15 14:54 UTC, DenysMoskalenko commented on app/routes.py
> +    return {'message': 'Recording will start reproducing shortly'}
По идее на момент отправки сообщения проигрывание записи уже началось. Тут же нет никакой очереди - тут паралельный таск

2022-12-15 14:54 UTC, DenysMoskalenko commented on app/routes.py
> +        file = s3_object_manager.get()['Body']
На этом этапе уже бросается в галза перегрузка роутов логикой s3.
Я б советовал винести всю обраточку s3 в отдельный класс, в котором написал бы нужные тебе методы, типо get_item, set_item и тд. В них-же была обработка разных ошибок.
В таком случае ты облегчишь роуты и при использовании s3 в других местах програмы не будт дублирования кода

2022-12-15 14:54 UTC, DenysMoskalenko commented on app/routes.py
> +        if e.response['Error']['Code'] == 'NoSuchKey':
По моему должна быть прям ошибка NoSuchKey.
Но могу ошибаться

2022-12-15 14:54 UTC, DenysMoskalenko commented on app/routes.py
> +        file = s3_object_manager.get()['Body']
Это не обязательно должен быть класс, это могут быть просто функции get_item, которые будут принимать ресурс, и которые будут делать все то-же самое что у тебя написанно тут, про это будет вынесенно из роутов.
(Я бы сделал так для простоты)

2022-12-15 14:54 UTC, DenysMoskalenko commented on app/background_tasks.py
> +        await socket_server.emit('reproduce', data=record, room=recording_id)
Напиши плиз какой вид имеет record приходящий на фронт?

2022-12-15 14:54 UTC, DenysMoskalenko commented on app/events.py
> +    print(f'connected {sid}')
Принта не должно быть в коде, если хочешь чет писать - используй логер

2022-12-15 14:54 UTC, DenysMoskalenko commented on app/events.py
> +from socketio import AsyncServer
Ты разобралась как работать с простыми функциями-ивентами, как я и говорил - все предельно просто
Давай теперь обернем это все под какой-то неймспейс. Название придумай чет связанное с машинками и используй класс для ивентов

2022-12-15 14:54 UTC, DenysMoskalenko commented on app/background_tasks.py
> +async def reproduce_recording(recording_id: str, file: StreamingBody):
Давай добавим логов типо "воспроизведение начато" "воспроизведение законченно".

2022-12-16 17:26 UTC, yelenskaya commented on app/background_tasks.py
> +        await socket_server.emit('reproduce', data=record, room=recording_id)
![image](https://user-images.githubusercontent.com/45938314/208154410-f6304594-8e5a-45bf-997b-dfbaad698807.png)

2022-12-16 17:30 UTC, yelenskaya commented on app/routes.py
> +    return {'message': 'Recording will start reproducing shortly'}
Там написано, что бекграунд таск запускается после отправки респонса:
![image](https://user-images.githubusercontent.com/45938314/208155059-e0885356-a41c-419e-a9ab-0b490a96ada0.png)
https://fastapi.tiangolo.com/tutorial/background-tasks/

2022-12-16 17:30 UTC, yelenskaya commented on app/routes.py
> +        if e.response['Error']['Code'] == 'NoSuchKey':
Она-то да, но ее никак не импортнуть

2022-12-17 16:54 UTC, DenysMoskalenko commented on app/routes.py
> +    return {'message': 'Recording will start reproducing shortly'}
Я к тому, что пока клиент получит это сообщение, таск уже начнет чет делать и логичнее дать ответ "Воспроизведение начато". Что по сути и будет происходить на самом деле.
Если б ты имела какую-то очередь, где этот таск мог б там провисеть минуту, тогда логичнее писать, как ты писала

2022-12-19 16:14 UTC, DenysMoskalenko requested changes

2022-12-19 16:14 UTC, DenysMoskalenko commented on app/s3_manager.py
> +        file = get_s3_resource().Object(bucket, object_key).get()['Body']
передавай ресурс непосредственно в функцию, не создавай его внутри

2022-12-19 16:14 UTC, DenysMoskalenko commented on app/routes.py
> +        raise HTTPException(status_code=500, detail='Failed to get the file from S3')
На уровне роута тебе не нужно знать про ClientError.
Ты можешь вызывать в своем менеджере абстрактную S3Error и ограничится тут одним except - для роута этого будет достаточно. А меседж и статус код хендлить в самой функции.
Если хочешь в функциях вызывать более подробную S3FileNotFoundError - можешь унаследовать её от S3Error (но в нашем случае от этого нет особого смысла)

Как вариант 1 - чтоб было удобно прокидывать статус код, можно в S3Error, например при ините дописать status_code параметр.
Как вариант 2 - так сказать fast-fail. Если у тебя уже вызывается ClientError которая отпадает потому что ты не можешь связаться с амазоном, то для FE нет особой разницы отдашь ты обработанную 500 или стандартную при обычной ошибке питона. Так что можно впринцп этот момент убрать совсем

2022-12-19 16:22 UTC, yelenskaya commented on app/background_tasks.py
> +        await socket_server.emit('reproduce', data=record, room=recording_id, namespace=RECORDING_NAMESPACE)
Добавлю в ПР с неймспейсом

2022-12-19 16:39 UTC, yelenskaya commented on app/routes.py
> +        raise HTTPException(status_code=500, detail='Failed to get the file from S3')
Пока просто оставила с3 эррор, без статуса, чтоб не связывать его с роутами

2022-12-19 17:19 UTC, merged