SNS connection between services
yelenskaya/carRecording pull request #9
Opened 2023-01-17 15:45 UTC by yelenskaya

2023-01-17 16:18 UTC, DenysMoskalenko requested changes

2023-01-17 16:18 UTC, DenysMoskalenko commented on recording/app/sns_publisher.py
> +def publish_message_as_json(topic_arn: str, message_json: str) -> str:
тебе не нужно пиать message_json. Если ты ожидаешь JSON добавь просто тип message: dict.
Если ты хочешь строку - пусть это будет любая строка.
Не нужно чтоб имя параметра у тебя отвечало за структуру, которую ты ожидаешь.
Ты ж не писала б message_dict. Тут тоже самое

2023-01-17 16:18 UTC, DenysMoskalenko commented on websocket/app/routes.py
> +    return message
убери это из роутов

2023-01-17 16:39 UTC, yelenskaya commented on websocket/app/main.py
> +    websocket_url = f'{_settings.WEBSOCKET_SERVICE_PROTOCOL}://{_settings.WEBSOCKET_SERVICE_HOST}'
Это потому что ngrok всегда превращает урлу в  https, а если локально запускать - выходит http, подумала что так будет удобнее

2023-01-18 09:58 UTC, DenysMoskalenko approved these changes

2023-01-18 10:19 UTC, merged